version: 2
jobs:
  build:
    working_directory: ~/circleci
    docker:
      - image: circleci/openjdk:8-jdk
      - image: selenium/standalone-chrome-debug:3.6.0

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - setup_remote_docker
#      - run: docker run -d -P -p 4444:4444 selenium/standalone-chrome-debug

      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn clean test

      - store_test_results:
                path: target/surefire-reports